<?php
session_start();
$title = "Reports";

if (!isset($_SESSION['user_id'])) {
    header('Location: login.php');
    exit;
}
require_once 'head.php';
require_once 'config.php';

// Use the existing connection from config.php
$pdo = $conn;

try {
    // Verify connection is still active
    $pdo->query('SELECT 1');
} catch(PDOException $e) {
    die("Database connection failed: " . $e->getMessage());
}

// Get document counts
$reportsCount = $pdo->query("SELECT COUNT(*) FROM documents WHERE document_type = 'complaint'")->fetchColumn();
$complaintCount = $pdo->query("SELECT COUNT(*) FROM documents WHERE document_type = 'both'")->fetchColumn();
$blotterCount = $pdo->query("SELECT COUNT(*) FROM documents WHERE document_type = 'blotter'")->fetchColumn();

// Get all documents with case and blotter details
$stmt = $pdo->query("SELECT d.*, b.id as blotter_id, b.c_name, b.r_name, b.date_time, b.status, 
                      u.username
                      FROM documents d
                      JOIN blotter b ON d.case_id = b.id
                      JOIN users u ON d.generated_by = u.user_id
                      ORDER BY d.generated_at DESC");
$documents = $stmt->fetchAll();
?>
<div class="flex flex-col w-full gap-2">
    <!-- Status Counter -->
    <div class="grid grid-cols-9 p-2 gap-3">
        <div class="bg-white rounded-md shadow-md p-2 grid grid-rows-2">
            <div class="text-sm text-gray-500 mt-3">Reports</div>
            <div class="text-xl font-semibold "><?= $reportsCount ?></div>
        </div>
        <div class="bg-white rounded-md shadow-md p-2 grid grid-rows-2">
            <div class="text-sm text-gray-500 mt-3">Complaint</div>
            <div class="text-xl font-semibold "><?= $complaintCount ?></div>
        </div>
        <div class="bg-white rounded-md shadow-md p-2 grid grid-rows-2">
            <div class="text-sm text-gray-500 mt-3">Blotter</div>
            <div class="text-xl font-semibold "><?= $blotterCount ?></div>
        </div>
    </div>
    <hr class=" border-gray-300">
    <!-- Buttons -->
    <div class="flex items-center mb-2 gap-3">
        <button onclick="openReportModal()" class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg transition-colors">
            <i class="fas fa-plus mr-2"></i>Generate Report
        </button>
    </div>
    <?php include 'generate_report_modal.php'; ?>
    <!-- Blotter Filter -->
    <div class="bg-white rounded-lg inset-shadow-md shadow-md p-3 md:p-5">
        <div class="px-4 py-3 flex flex-col md:flex-row justify-between items-start md:items-center bg-gray-50 gap-4">
            <div class="flex flex-col md:flex-row items-start md:items-center gap-2 w-full md:w-auto">
                <label class="text-sm">Filter:</label>
                <select class="border rounded px-2 py-1 text-sm w-full md:w-auto" id="statusFilter">
                    <option value="all">All Types</option>
                    <option value="resolved">Both</option>
                    <option value="1st trial">Blotter</option>
                    <option value="2nd trial">Complaint</option>
                </select>
            </div>
            <div class="relative w-full md:w-auto">
                <input type="text" placeholder="Search..." class="border rounded px-3 py-1 text-sm w-full" id="searchInput">
            </div>
        </div>
        <!-- Blotter Table -->
        <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200 table-fixed">
                <thead class="bg-gray-50">
                    <tr>
                        <th class="px-3 md:px-6 py-3 w-1/16 text-left text-xs font-medium text-gray-500 uppercase tracking-wider cursor-pointer" onclick="sortTable(0)"># <i class="fas fa-sort"></i></th>
                        <th class="px-3 md:px-6 py-3 w-1/12 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Case No.</th>
                        <th class="px-3 md:px-6 py-3 w-1/6 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Complainant</th>
                        <th class="px-3 md:px-6 py-3 w-1/6 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Respondent</th>
                        <th class="px-3 md:px-6 py-3 w-1/12 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
                        <th class="px-3 md:px-6 py-3 w-1/8 text-left text-xs font-medium text-gray-500 uppercase tracking-wider cursor-pointer" onclick="sortTable(1)">Incident Date <i class="fas fa-sort"></i></th>
                        <th class="px-3 md:px-6 py-3 w-1/8 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Generated By</th>
                        <th class="px-3 md:px-6 py-3 w-1/8 text-left text-xs font-medium text-gray-500 uppercase tracking-wider cursor-pointer" onclick="sortTable(2)">Generated Date <i class="fas fa-sort"></i></th>
                        <th class="px-3 md:px-6 py-3 w-1/8 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Action</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200" id="complaintsTable">
                    <?php                
// Pagination logic
$itemsPerPage = 10;
$currentPage = isset($_GET['page']) ? (int)$_GET['page'] : 1;
$totalDocuments = count($documents);
$totalPages = ceil($totalDocuments / $itemsPerPage);
$currentPage = max(1, min($currentPage, $totalPages));
$offset = ($currentPage - 1) * $itemsPerPage;
$paginatedDocuments = array_slice($documents, $offset, $itemsPerPage);

foreach($paginatedDocuments as $document):
    $typeColor = [
        'complaint' => 'bg-blue-100 text-blue-800',
        'summon' => 'bg-purple-100 text-purple-800',
        'cfa' => 'bg-red-100 text-red-800'
    ][$document['document_type']] ?? 'bg-gray-100 text-gray-800';
?>
<tr>
    <td class="px-3 md:px-6 py-4 whitespace-nowrap text-sm text-gray-500 w-1/16"><?= $offset + array_search($document, $paginatedDocuments) + 1 ?></td>
    <td class="px-3 md:px-6 py-4 whitespace-nowrap text-sm text-gray-500 w-1/12">B-<?= $document['case_id'] ?></td>
    <td class="px-3 md:px-6 py-4 whitespace-nowrap text-sm text-gray-500 w-1/6"><?= $document['c_name'] ?></td>
    <td class="px-3 md:px-6 py-4 whitespace-nowrap text-sm text-gray-500 w-1/6"><?= $document['r_name'] ?></td>
    <td class="px-3 md:px-6 py-4 whitespace-nowrap text-sm w-1/12">
        <span class="px-2 py-1 rounded-full text-xs font-semibold <?= $typeColor ?>">
            <?= ucfirst($document['document_type']) ?>
        </span>
    </td>
    <td class="px-3 md:px-6 py-4 whitespace-nowrap text-sm text-gray-500 w-1/8"><?= date('M d, Y', strtotime($document['date_time'])) ?></td>
    <td class="px-3 md:px-6 py-4 whitespace-nowrap text-sm text-gray-500 w-1/8"><?= $document['username'] ?></td>
    <td class="px-3 md:px-6 py-4 whitespace-nowrap text-sm text-gray-500 w-1/8"><?= date('M d, Y', strtotime($document['generated_at'])) ?></td>
    <td class="px-3 md:px-6 py-4 whitespace-nowrap text-sm text-gray-500 w-1/8">
        <a href="<?= $document['file_path'] ?>" class="text-blue-600 hover:text-blue-900" download>
            <i class="fas fa-download mr-1"></i>Download
        </a>
    </td>
</tr>
<?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="px-4 py-2 flex items-center justify-between border-t border-gray-200 bg-gray-50">
            <div class="flex-1 flex justify-between sm:hidden">
                <a href="#" class="relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50">Previous</a>
                <a href="#" class="ml-3 relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50">Next</a>
            </div>
            <div class="hidden sm:flex-1 sm:flex sm:items-center sm:justify-between">
                <div>
                    <p class="text-sm text-gray-700">
                        Showing <span class="font-medium"><?= $offset + 1 ?></span> to <span class="font-medium"><?= min($offset + $itemsPerPage, count($documents)) ?></span> of <span class="font-medium"><?= count($documents) ?></span> results
                    </p>
                </div>
                <div>
                    <nav class="relative z-0 inline-flex rounded-md shadow-sm -space-x-px" aria-label="Pagination">
                        <a href="?page=<?= max(1, $currentPage - 1) ?>" class="relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 <?= $currentPage == 1 ? 'opacity-50 cursor-not-allowed' : '' ?>">
                            <span class="sr-only">Previous</span>
                            <i class="fas fa-chevron-left"></i>
                        </a>
                        <?php for ($i = 1; $i <= $totalPages; $i++): ?>
                            <a href="?page=<?= $i ?>" class="relative inline-flex items-center px-4 py-2 border text-sm font-medium <?= $i == $currentPage ? 'bg-blue-50 border-blue-500 text-blue-600' : 'bg-white border-gray-300 text-gray-500 hover:bg-gray-50' ?>">
                                <?= $i ?>
                            </a>
                        <?php endfor; ?>
                        <a href="?page=<?= min($totalPages, $currentPage + 1) ?>" class="relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 <?= $currentPage == $totalPages ? 'opacity-50 cursor-not-allowed' : '' ?>">
                            <span class="sr-only">Next</span>
                            <i class="fas fa-chevron-right"></i>
                        </a>
                    </nav>
                </div>
            </div>
        </div>